language: go
go:
- 1.12.x
services:
- docker
install:
- go get
before_script:
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o traffic-monitor
script:
- go test
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master
    tags: true
env:
  global:
  - GO111MODULE=on
  - secure: cMhGYzM26baFqA/fWlwXOkj4f+KCFtf9OiAHpgTM01FTDIeA0k4X53QMKiUekR2KqEuLRl6gQ5BZdFR0PoBHFBkOcAFnoGnIJHwfw86X+fQRKRMCu/mo4xjWXiCE1s9EstJB4JnCA8wIhxosVRjMEkBYcQcORWHEqzNbAUOMHCR05rHIJJM5OMGUZCgTpoHZvBMsy6tp2aZgm2743xhzfQQkiWH69HOLd0NB2B4MUhZ4y6tZW4Mh5ZgRjxhR4KejUiTlNyjT9ARgMemyyiUvrlvSMM4GbbzY1MwFIh9EuYgsK/So2bZ0ZbbofyUNbbp7NkYRNP4V149JGg1uPUj1F8868ftsPM7qj2suVhtJx23ui01rtWwBO0irsxqEkrgl4dWut8ZtUS8neGAiU9T7TPOU/l6WzHw9q8xUgByw2B/GscEf8SYbUZnI5rSUtqOT6CHMR/bfF+KpJ7BAq+IOwEOb3BJTfLe6Id03M4HxJ5hV2VaZ3gbpGErn4mTBB0JI/Jcij0MbWRfDQfj3sFRTl8xcpqW4TRlqfElLd6V0a/sAWlsE9IGKUh9DDCUobOTE1j06HcjRP8Nn7by1jjenYftoeBlekBmxv/Bb3vOwUJQRzpK7O1LmXvu2kVbWzkkgWP7tzClip+lm7gJynwQNolhtIXXHfagbOqIsnoJBMlE=
  - secure: L7V+mNbqoDz57gbRdr3a35os9zGMuImZIwHhCNH2Hw8pCnf3hsfNs7soTLroqHrudzIbQ+wVol2YDzQVN0wL+hhayDowaG1vnPWWmxAcgUYRxzRTrZk9r/eHs7Lk9bkqWd0laNZD+LAAlFmi/qG+gJU905VPngk3XFU8uqpp9CHuPT1yehdQms0wbQlvyApZ9bL7hgGX0UUOEn1CfU5cgtUTLqXbK1CfaZihxo9eLlOD/pa07O/YUD/VNLziPPkGmkq+GICkArjL18Pyxby4eIfyEKT7f3zmmfhSeQsqhrQJhgiw7g54sdLwclmJuz7uK2e+OmR1UEyrUa7JQPrwSuu/3wvQ+I9txIjyU8RRHCuvaCBTkkrfYGS4aXxhpx3ucT75RCrQPH4R2w/86yrrojAQqWlRfb462n0hiQz8rmVdCA1GpNvs2LLpkltOi23KMzNUh2N9bckL5Uc7m2zBAszSR30J6U6PlWiacoKJyB6/S9yACbnkvkYzvuvvMktIa8OW5XywZt7XjQrl5GcUzHURcoimvP/fIhFF42+Z5caIJLq8RaH+Zq6EyxmM59T0dqv5dsB1HHJIirGY/A3c9kEyaLKuTuiL784ntXje5X9rR/M6iW9duxqW4vrYsTi28F7YmLfaPoF4PPkSXZ5lYpNkTQ+5lLMCNsDzvNkSSIY=
