language: go
go:
- 1.12.x
services:
- docker
install:
- go get
before_script:
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o traffic-monitor
script:
- go test
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master
    tags: true
env:
  global:
  - GO111MODULE=on
  - DOCKER_USERNAME=doriancz
  - secure: CjIMU3DB0qIIxhsz52gR5AIQou+ma5TcdyfPrKVdYVPzsJWEEayddr4r87UV5vKUkN8VDCbcmo79XYm2cgZjPo7qT/faJ6ag0/ZQbJGZlTNM5cyI3m5jdzEfcyf1jyGHGXQO3fhtncsFB6Sn25sHrYvUQreeIDPf8Jjox/htebWBRA3EqaCGTrAG5qBSgSuaWlGP/H09yG+RaeDerTB0KMpm8V7A2J3HX/+p6NFxCwAJhb3xeIbrZKO8bD6lxZSe5DljV0jqW7oUvs3pjUxgP8wGhG4+7qnef6KTCN8GiTPJwHxW7Ppv0+rLg2w4EfHb1o38efYB9iSIDD+x6ypB2fwBNwtFD1Jak5cFLFYgFyIlSTbJ+K9gERG7uHkXRSaKsgKiphtkk4UYu+PhEatt3ahi8zSh5IVE4FOHkt6MbWD249w2uSUguiW6+/9u2OObHOQ4GoPWKEatR+rDQ+S7IaRfKyb3qximRlYxNhYihQG0cvzNwaOoOsi/RNc46As/Xo+ZP1pBRZNF1p+hho4k0/MPRnieumTTG6EfNjaZ3CXAHanMFF/yQ0KmlD+wwhOfqNSIfavu1YW0VJwbUqk7UopfZOwY8GvS7ifNK/uXtbIAO4wpvZN68MC2iqgrLFEHaeYAT+liuRd0PJIZf5BlxPHL8M3ecISmjmwVDxwWX7k=